[package]
name = "fobnail"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(target_os = "none")'.dependencies]
pal_nrf = { path = "pal/pal_nrf" }
smoltcp = { version = "0.7.5", default-features = false, features = ["alloc", "proto-ipv4", "socket-udp", "ethernet", "log"] }

[target.'cfg(target_os = "linux")'.dependencies]
pal_pc = { path = "pal/pal_pc" }
smoltcp = { version = "0.7.5", default-features = false, features = ["proto-ipv4", "socket-udp", "ethernet", "log"] }

[dependencies]
log = { version = "0.4", default-features = false, features = ["max_level_trace"] }
coap-lite = { version = "0.7", default-features = false }
