name: Build Fobnail binaries

on:
  push:

env:
  FOBNAIL_SDK_VERSION: v0.2.6

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Download run-fobnail-sdk script
        run: |
          wget https://raw.githubusercontent.com/fobnail/fobnail-sdk/${FOBNAIL_SDK_VERSION}/run-fobnail-sdk.sh
          chmod +x ./run-fobnail-sdk.sh

      - name: Install dummy Platform Owner root certificate
        run: |
          cat <<EOF > $RUNNER_TEMP/root.crt
          -----BEGIN CERTIFICATE-----
          MIIDrDCCApSgAwIBAgIUIRSoyB/JQj3aOV00vUZ0DROsQMAwDQYJKoZIhvcNAQEL
          BQAwXDELMAkGA1UEBhMCUEwxEDAOBgNVBAoMB0ZvYm5haWwxDjAMBgNVBAgMBVN0
          YXRlMSswKQYDVQQDDCJQbGF0Zm9ybSBPd25lciByb290IENBIGNlcnRpZmljYXRl
          MB4XDTIyMDQyODA2NTkxMloXDTIzMDQyODA2NTkxMlowXDELMAkGA1UEBhMCUEwx
          EDAOBgNVBAoMB0ZvYm5haWwxDjAMBgNVBAgMBVN0YXRlMSswKQYDVQQDDCJQbGF0
          Zm9ybSBPd25lciByb290IENBIGNlcnRpZmljYXRlMIIBIjANBgkqhkiG9w0BAQEF
          AAOCAQ8AMIIBCgKCAQEAqVojh0w4U7vOz97A04QfokxaiIZ+Iu3I7ENCH/JFBLyu
          MDtHa0SxaBWqud6FoOS5hsypxc+3Qsp0PQutIbDYjWpnPDES6ZqCJoyLLNjZUZ7y
          huoaVvRbMZg9CdtIR/JRXSd0UP+miswbPb/RUN/bep4SVp+keIxNUq/jEx+ht3Yi
          HaAzVB8BqSeQnmaxesH+2SDi4LU9yCfzdINVJJyEpeGRC39aC12755n6ku3G5Y8t
          vhVM+lNe3pxISP8D7fyF+ZaUBYbRLo2LnuRmz1aqz+1ZqhsjfwiUuGYCSdEHsw++
          u5XsUWi2ULFiZFo2dUvmcnejmTDSKYs3A8ZbpkNbGwIDAQABo2YwZDASBgNVHRMB
          Af8ECDAGAQH/AgEBMA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQUYxcgeGZfchsN
          E6Ze3ydPIK4dyqswHwYDVR0jBBgwFoAUYxcgeGZfchsNE6Ze3ydPIK4dyqswDQYJ
          KoZIhvcNAQELBQADggEBAExZaTrUjdf2S/2ESRgDFdbNQnmehh23VsgeElhd8rjx
          AxhEyAy8JJT4RQk07OzB3WsooHw1NhzX4l3HyDnexoUrudYiEfWvNL2LFS3rU4O5
          9hKzdDOv0Jk5nqY5a3WH6QpJHz1BenKNTGCs4oKiiuAym0ludkWIXhDSCelQKGK1
          jpoQJ90AS08tFpaNCcXt7mvFBs4LD5TEq8UrGmaf1YwrFK7xnmJUoYMKjui8CTr0
          rtlmg7rmMCq9l9aorxnTdZwlqBanczyaQqVbLLwOgRdG/xwF14vkZRgQ4j+VQutk
          qqzVvULVa9bA9obA1q8zEgXpTUWVgmwaj0p+RIQbYpk=
          -----END CERTIFICATE-----
          EOF

      - name: Build for PC target
        run: |
          export PATH=$PWD:$PATH
          export FOBNAIL_PO_ROOT=$RUNNER_TEMP/root.crt
          ./build.sh --target pc

      - name: Build for nRF52 target
        run: |
          export PATH=$PWD:$PATH
          export FOBNAIL_PO_ROOT=$RUNNER_TEMP/root.crt
          ./build.sh --target nrf
